### ISSUE TITLE
cluster step

### ISSUE THREAD

**Issue by Tim4AI** [SomeoneDistant/Lightweight-Face-Recognition#2]
thanks your good job. i have read the paper and code, but i can not find the cluster step in your code, the "pseudo full connection" is your cluster step ?

**Comment by SomeoneDistant** [comment]
Thanks. We are still reorganizing the codes and the clustering part is not included in this repo now. 
Pseudo FC is a trick to reduce computation consumption.

**Comment by Tim4AI** [comment]
Ok, thanks
